name: SimpleStaffChat
version: ${project.version}
main: me.crazybanana.simplestaffchat.SimpleStaffChat
api-version: 1.16
authors: [CrazyBanana]
description: This is a very simple plugin that implements staff chat
