name: SimpleStaffChat
version: 1.0.3
main: me.crazybanana.simplestaffchat.SimpleStaffChat
api-version: 1.16
authors: [CrazyBanana]
description: This is a very simple plugin that implements staff chat
permissions:
  simplestaffchat.use:
    default: op
    description: Allows use of chatting in staff chat through either the command and the character.
  simplestaffchat.reload:
    default: op
    description: Allows you to reload the plugin.
commands:
  staffchat: # ../me/crazybanana/simplestaffchat/commands/staffchat.java
    description: Main command for the plugin
    aliases: [sc]
  staffchatreload: # ../me/crazybanana/simplestaffchat/commands/staffchatreload.java
    description: Reload the config file for this plugin
    aliases: [scr, screload]
